# 1. Create a 3x3x3 array with random values 

In [ ]:
import numpy as np


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
b=np.diag([1,2,3,4])
print(b)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
c = np.ones((3,3))
print("Checkerboard pattern:")
c = np.zeros((8,8),dtype=int)
c[1::2,::2] = 1
c[::2,1::2] = 1
print(c)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [20]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)


False


# 5.  How to find common values between two arrays?

In [20]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [23]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

TypeError: int() takes at most 2 arguments (3 given)

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [24]:
a = np.random.random(10)
print("Original array:")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Original array:
[0.8146269  0.04245418 0.13777787 0.55171709 0.60155875 0.96304094
 0.44786563 0.30738907 0.3595992  0.6254103 ]
Maximum value replaced by 0:
[0.8146269  0.04245418 0.13777787 0.55171709 0.60155875 0.
 0.44786563 0.30738907 0.3595992  0.6254103 ]


# 9. How to print all the values of an array?

In [5]:
import numpy as np


In [6]:
my_array = np. arange(1001)
print(my_array)
np. set_printoptions(threshold=np. inf)
print(my_array)

[   0    1    2 ...  998  999 1000]
[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189 

# 10.Subtract the mean of each row of a matrix

In [19]:
x= np.array([[8,7],[5,6]], dtype=np.float64)
y= np.array([[4,3],[2,1]], dtype=np.float64)
print (x - y)
print (np.subtract(x,y))


[[4. 4.]
 [3. 5.]]
[[4. 4.]
 [3. 5.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 3. 2. 2. 3. 4. 2. 4. 4.]


# 12.How to get the diagonal of a dot product?

In [22]:
A = np.random.randint(0,10,(3,3))
B = np.random.randint(0,10,(3,3))
np.diag(np.dot(A, B))

array([ 5, 14, 86])

# 13.How to find the most frequent value in an array?

In [23]:
Z = np.random.randint(0,10,30)
print (Z)
print('rank:', np.bincount(Z).argmax())

[4 6 1 8 1 8 7 5 1 2 0 8 2 6 0 1 4 9 1 1 8 1 9 0 2 2 7 2 3 0]
rank: 1


# 14.How to get the n largest values of an array

In [24]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])


[95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [25]:
arra1 = np.array([("Ram", 88.5, 90),
                 ("Raju", 87, 99),
             ("Raghav", 85.5, 91)])
print("Original arrays:")
print(arra1)


Original arrays:
[['Ram' '88.5' '90']
 ['Raju' '87' '99']
 ['Raghav' '85.5' '91']]


In [26]:
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)


Record array;
[(b'Ram', 88.5, 90) (b'Raju', 87. , 99) (b'Raghav', 85.5, 91)]
